/** Scene */
export const SCENE_MAIN_TITLE = 'SCENE_MAIN_TITLE'
export const SCENE_MAIN_PROLOG = 'SCENE_MAIN_PROLOG'
export const SCENE_MAIN_CHARACTER = 'SCENE_MAIN_CHARACTER'
export const SCENE_PLAY_GAME = 'SCENE_PLAY_GAME'
/** */
